/*
Deployment script for ModelHighSchool

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ModelHighSchool"
:setvar DefaultFilePrefix "ModelHighSchool"
:setvar DefaultDataPath "c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[parent_tb]...';


GO
CREATE TABLE [dbo].[parent_tb] (
    [parent_id]                 INT          NOT NULL,
    [parent_father_firstname]   VARCHAR (45) NOT NULL,
    [parent_father_middlename]  VARCHAR (45) NULL,
    [parent_father_surname]     VARCHAR (45) NOT NULL,
    [parent_mother_firstname]   VARCHAR (45) NOT NULL,
    [parent_mother_middlename]  VARCHAR (45) NULL,
    [parent_mother_surname]     VARCHAR (45) NOT NULL,
    [parent_gardian_firstname]  VARCHAR (45) NULL,
    [parent_gardian_middlename] VARCHAR (45) NULL,
    [parent_gardian_lastname]   VARCHAR (45) NULL,
    [parent_phone]              VARCHAR (15) NOT NULL,
    [parent_mobile]             VARCHAR (15) NULL,
    [reationship_id]            INT          NOT NULL,
    [parent_date_created]       DATE         NOT NULL,
    [parent_date_deleted]       DATE         NULL,
    PRIMARY KEY CLUSTERED ([parent_father_firstname] ASC, [parent_phone] ASC),
    UNIQUE NONCLUSTERED ([parent_id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
