//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_tb
    {
        public class_tb()
        {
            this.classstudents_tb = new HashSet<classstudents_tb>();
        }
    
        public int class_id { get; set; }
        public int @class { get; set; }
        public string section { get; set; }
        public int school_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual schools_tb schools_tb { get; set; }
        public virtual ICollection<classstudents_tb> classstudents_tb { get; set; }
    }
}
