//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diary_tb
    {
        public diary_tb()
        {
            this.diarynotes_tb = new HashSet<diarynotes_tb>();
        }
    
        public string diaryno { get; set; }
        public int student_id { get; set; }
        public int note_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual student_tb student_tb { get; set; }
        public virtual ICollection<diarynotes_tb> diarynotes_tb { get; set; }
    }
}
