//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diarynotes_tb
    {
        public int diarynotes_id { get; set; }
        public string diaryno { get; set; }
        public int note_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
        public int school_id { get; set; }
    
        public virtual note_tb note_tb { get; set; }
        public virtual diary_tb diary_tb { get; set; }
    }
}
