//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note_tb
    {
        public note_tb()
        {
            this.remark_tb = new HashSet<remark_tb>();
            this.notedata_tb = new HashSet<notedata_tb>();
            this.diarynotes_tb = new HashSet<diarynotes_tb>();
        }
    
        public int note_id { get; set; }
        public int user_id { get; set; }
        public int school_id { get; set; }
        public string notehealine { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual schools_tb schools_tb { get; set; }
        public virtual ICollection<remark_tb> remark_tb { get; set; }
        public virtual ICollection<notedata_tb> notedata_tb { get; set; }
        public virtual ICollection<diarynotes_tb> diarynotes_tb { get; set; }
    }
}
