//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remark_tb
    {
        public remark_tb()
        {
            this.remarkdata_tb = new HashSet<remarkdata_tb>();
        }
    
        public int remark_id { get; set; }
        public int user_id { get; set; }
        public int note_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual note_tb note_tb { get; set; }
        public virtual ICollection<remarkdata_tb> remarkdata_tb { get; set; }
    }
}
