//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remarkdata_tb
    {
        public int remarkdata_id { get; set; }
        public int remark_id { get; set; }
        public string remarktext { get; set; }
        public byte[] remarkimage { get; set; }
        public byte[] remarkmedia { get; set; }
    
        public virtual remark_tb remark_tb { get; set; }
    }
}
