//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools_tb
    {
        public schools_tb()
        {
            this.class_tb = new HashSet<class_tb>();
            this.note_tb = new HashSet<note_tb>();
            this.student_tb = new HashSet<student_tb>();
            this.subsciption_tb = new HashSet<subsciption_tb>();
            this.user_tb = new HashSet<user_tb>();
        }
    
        public int school_id { get; set; }
        public string school_name { get; set; }
        public string city_name { get; set; }
        public string province_name { get; set; }
        public string country_name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual ICollection<class_tb> class_tb { get; set; }
        public virtual ICollection<note_tb> note_tb { get; set; }
        public virtual ICollection<student_tb> student_tb { get; set; }
        public virtual ICollection<subsciption_tb> subsciption_tb { get; set; }
        public virtual ICollection<user_tb> user_tb { get; set; }
    }
}
