//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DairyDBEntities : DbContext
    {
        public DairyDBEntities()
            : base("name=DairyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<schools_tb> schools_tb { get; set; }
        public DbSet<student_tb> student_tb { get; set; }
        public DbSet<user_tb> user_tb { get; set; }
        public DbSet<class_tb> class_tb { get; set; }
        public DbSet<note_tb> note_tb { get; set; }
        public DbSet<remark_tb> remark_tb { get; set; }
        public DbSet<subsciption_tb> subsciption_tb { get; set; }
        public DbSet<classstudents_tb> classstudents_tb { get; set; }
        public DbSet<notedata_tb> notedata_tb { get; set; }
        public DbSet<remarkdata_tb> remarkdata_tb { get; set; }
        public DbSet<diary_tb> diary_tb { get; set; }
        public DbSet<diarynotes_tb> diarynotes_tb { get; set; }
    
        public virtual int searchschool_by_city_pro(string city)
        {
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("searchschool_by_city_pro", cityParameter);
        }
    
        public virtual int searchschool_by_id_pro(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("searchschool_by_id_pro", idParameter);
        }
    }
}
