//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_tb
    {
        public int student_id { get; set; }
        public int user_id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public int rollno { get; set; }
        public int class_id { get; set; }
        public int school_id { get; set; }
        public string address { get; set; }
        public string remarks { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
        public string sex { get; set; }
    
        public virtual schools_tb schools_tb { get; set; }
        public virtual user_tb user_tb { get; set; }
        public virtual diary_tb diary_tb { get; set; }
    }
}
