//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tb
    {
        public user_tb()
        {
            this.student_tb = new HashSet<student_tb>();
        }
    
        public int user_id { get; set; }
        public int school_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string type { get; set; }
        public string phoneno { get; set; }
        public string mobileno { get; set; }
        public string address { get; set; }
        public string relation { get; set; }
        public string remarks { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    
        public virtual schools_tb schools_tb { get; set; }
        public virtual ICollection<student_tb> student_tb { get; set; }
    }
}
